[build]
  command = "curl -fsSL https://deno.land/install.sh | sh && export DENO_INSTALL=$HOME/.deno && export PATH=$DENO_INSTALL/bin:$PATH && deno task build"
  publish = "_site"
  
[functions]
  directory = "netlify/functions"

