option(ASAN "Enable Address Sanitizer" OFF)
option(TSAN "Enable Thread Sanitizer" OFF)
option(UBSAN "Enable Undefined Behavior Sanitizer" OFF)

if (ASAN AND TSAN)
  message(FATAL_ERROR "ASAN and TSAN cannot be enabled simultaneously")
endif()

if (UBSAN AND NOT ASAN)
  message(STATUS "Sanitize with UB Sanitizer (UBSAN)")
  add_compile_options(-fsanitize=undefined -fno-sanitize-recover=all)
  add_link_options(-fsanitize=undefined)
endif ()

if (ASAN)
  message(STATUS "Sanitize with Address Sanitizer (ASAN + UBSAN)")
  add_compile_options(-fsanitize=address,undefined -fno-sanitize-recover=all)
  add_link_options(-fsanitize=address,undefined)
endif ()

if (TSAN)
  message(STATUS "Sanitize with Thread Sanitizer (TSAN)")
  add_compile_options(-fsanitize=thread -fno-sanitize-recover=all)
  add_link_options(-fsanitize=thread)
endif ()
